// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmhxyquaxgyfttmfmmab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtaHh5cXVheGd5ZnR0bWZtbWFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDQ5NTksImV4cCI6MjA3MTA4MDk1OX0.WUKSd4ObvlHjYVX5rJdRP4KWNj2MYlh7BKqslhleuuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});